name: GitHub Actions Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: jorgesoft/attack-website
          path: attack-website

      -  name: Set up QEMU
         uses: docker/setup-qemu-action@v1

      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

      -  name: Login to DockerHub
         uses: docker/login-action@v1
         with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Change RUN line in Dockerfile
        run: sed -i 's/  RUN python3 update-attack.py/  RUN python3 update-attack.py --no-test-exitstatus/' Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gorje6/attack-website:latest
